# Generated by Django 5.2.8 on 2025-11-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código interno del local', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('direccion', models.CharField(help_text='Calle y número', max_length=300, verbose_name='Dirección')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('region', models.CharField(max_length=100, verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ['codigo', 'nombre'],
            },
        ),
    ]
