# Generated by Django 5.2.8 on 2025-11-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='stock_min_dinamico',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock_actual',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock_seguridad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='categoria',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='material',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='ubicacion',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='material',
            name='unidad_medida',
            field=models.CharField(max_length=30),
        ),
    ]
