# Generated by Django 5.2.8 on 2025-11-26 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demanda_promedio', models.FloatField()),
                ('desviacion', models.FloatField()),
                ('leadtime_dias', models.IntegerField()),
                ('stock_min_calculado', models.IntegerField()),
                ('version_modelo', models.CharField(default='v1.0', max_length=40)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_ml', to='core.material')),
            ],
            options={
                'db_table': 'ml_result',
                'ordering': ['-fecha_calculo'],
            },
        ),
    ]
