# Generated by Django 5.2.8 on 2025-11-24 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_inventario_stock_min_dinamico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='descripcion',
            new_name='mensaje',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='alerta',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('stock_critico', 'Stock Crítico'), ('solicitud_pendiente', 'Solicitud Pendiente'), ('material_nuevo', 'Material Nuevo'), ('aprobacion', 'Aprobación Requerida')], default='material_nuevo', max_length=30),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
