# Generated by Django 5.2.8 on 2025-11-30 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='local_destino',
            field=models.ForeignKey(blank=True, help_text='Local donde se entregarán los materiales', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='core.local', verbose_name='Local de Destino'),
        ),
    ]
