# Generated by Django 5.2.8 on 2025-12-03 02:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_inventario_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
