# Generated by Django 5.2.8 on 2025-12-03 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_alerta_creado_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha']},
        ),
    ]
