# Generated by Django 5.2.8 on 2025-12-03 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_movimiento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.material'),
        ),
    ]
