# Generated by Django 5.2.8 on 2025-12-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_movimiento_material'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detallesolicitud',
            index=models.Index(fields=['solicitud', 'material'], name='core_detall_solicit_f702be_idx'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['material'], name='core_invent_materia_a7dbb0_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['estado', 'fecha_solicitud'], name='core_solici_estado_7a9068_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['solicitante'], name='core_solici_solicit_321815_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['estado', 'solicitante'], name='core_solici_estado_cc1b48_idx'),
        ),
    ]
