# Generated by Django 5.2.8 on 2025-12-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('GERENCIA', 'Gerencia'), ('BODEGA', 'Bodega'), ('TECNICO', 'Técnico'), ('SISTEMA', 'Sistema')], default='TECNICO', max_length=20, verbose_name='Rol'),
        ),
    ]
