# Generated by Django 5.2.8 on 2025-12-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlresult',
            name='coeficiente_variacion',
            field=models.FloatField(default=0.0, help_text='Variabilidad relativa (sigma/media)'),
        ),
        migrations.AddField(
            model_name='mlresult',
            name='metodo_utilizado',
            field=models.CharField(default='Estandar', max_length=50),
        ),
        migrations.AddField(
            model_name='mlresult',
            name='stock_seguridad',
            field=models.FloatField(default=0.0, help_text='Colchón extra por variabilidad'),
        ),
    ]
