# Generated by Django 5.2.8 on 2025-12-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_mlresult_coeficiente_variacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('GERENCIA', 'GERENCIA'), ('BODEGA', 'BODEGA'), ('TECNICO', 'TECNICO'), ('SISTEMA', 'SISTEMA')], default='TECNICO', max_length=20, verbose_name='Rol'),
        ),
    ]
