# Generated by Django 5.2.8 on 2025-12-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-creada_en'], 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AddField(
            model_name='local',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
