# Generated by Django 5.2.8 on 2025-12-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_notificacion_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidades'), ('kg', 'Kilogramos'), ('metro', 'Metros'), ('litro', 'Litros')], default='unidad', max_length=20),
        ),
    ]
